config/routes.rb
Rails.application.routes.draw do

  root :to => 'elements#home'
  get '/elements' => 'elements#index'
  get '/properties' => 'elements#property'
  get '/valencies' => 'elements#element_valencies'
  get '/compounds' => 'elements#compounds'
  get '/game' => 'elements#game'
  post '/compounds/molecule' => 'elements#molecule', as: 'element_molecule'
	
  resources :users 
  get 'signup' => 'users#new' 
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :scores

end

app/models/element.rb
class Element < ActiveRecord::Base
	has_and_belongs_to_many :valencies
	has_and_belongs_to_many :compounds

	#Function to convert all the valencies of an element in a string
	def self.order_valencies_in_a_string
		elements = Element.all
		valencies_array = []
		valencies_string = ''
		elements.each do |element|
			valencies_array << element_valencies(element) 
		end	
		valencies_array
	end

	def self.element_valencies(element)
		valencies = element.valencies
		valencies_string = ''
		valencies.each do |valency|
			valencies_string = valencies_string + create_valencies_string(valency, valencies)
		end
		return valencies_string
	end

	def self.create_valencies_string(valency, valencies)
		if last_valency(valency, valencies)
			valencies_string = valency.valence.to_s + ','
		else
			valencies_string = valency.valence.to_s
		end
		return valencies_string
	end

	def self.last_valency(valency, valencies)
		last_valency_index = valencies.length - 1
		valency.valence != valencies[last_valency_index].valence
	end


	#functions to calculate the molecular weight from a formula
	def self.calculate_weight(atoms_composition_object)
		array_atoms = []
		elements = ChemistryRails::ELEMENTS
		if atoms_composition_object == {}
			array_atoms = [nil]
		else 
			atoms_composition_object.each_key do |key|
				atom = find_atom_in_formula(elements, key)
				array_atoms << atom
			end
		end
		check_formula(array_atoms, atoms_composition_object, elements)
	end

	def self.find_atom_in_formula(elements, key)
		atom = elements.find do |element| 
			if element
				element[:short] == key
			end
		end
		return atom
	end

	def self.check_formula(array_atoms, atoms_composition_object, elements)
		if incorrect_formula(array_atoms)
			return 'Incorrect Simbols. Try again!'
		else
			mass = calculate_mass(atoms_composition_object, elements)
			return 'Molecular weight: ' + mass.to_f.round(4).to_s + ' g/mol'	
		end		
	end

	def self.calculate_mass(atoms_composition_object, elements)
			mass = 0
			atoms_composition_object.each_key do |key|
				atom = find_atom_in_formula(elements, key)

				atom_mass = atom[:mass]
				atoms_number = atoms_composition_object[key]
				mass += atom_mass * atoms_number
			end
			return mass
	end

	def self.incorrect_formula(atoms)
		atoms.include? nil
	end
	
	def self.matrix_periodic_table
		return [
			[1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1],
			[1,1,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1],
			[1,1,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1],
			[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
			[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
			[1,1,6,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
			[1,1,6,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
			[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
			[0,0,5,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
			[0,0,5,4,1,1,1,1,1,1,1,1,1,1,1,1,1,1]]
	end
end

app/controllers/elements_controller.rb
class ElementsController < ApplicationController
	def home	
	end

	def index
		@elements = Element.all	
		@matrix_elements = Element.matrix_periodic_table	
		@categories = ChemistryRails::ELEMENT_CATEGORIES #creo que esto no es necesario
	end

	def compounds
		@elements = Element.all	
		@matrix_elements = Element.matrix_periodic_table
	end

	def game
		@elements = Element.all	
		@matrix_elements = Element.matrix_periodic_table
	end
	
	def property
		@elements = Element.all
		render json: @elements
	end

	def element_valencies
		@valencies = Element.order_valencies_in_a_string
		render json: @valencies
	end

	def molecule
		@elements = Element.all	
		@matrix_elements = Element.matrix_periodic_table
		@formula = ChemistryRails::Formula.new(params[:molecule]) 
		@formula_elements = @formula.elements
		@molecular_weight = Element.calculate_weight(@formula_elements)
		render 'compounds'
	end

end

app/helpers/elements_helper.rb
module ElementsHelper
	def element_configuration(element_electron_configuration)
	  if element_electron_configuration
	    elec_config_element = element_electron_configuration
	    length = elec_config_element.length-2
	    new_conf = elec_config_element.clone
	    if_need_sup = false 
	    new_conf_pos = 0
	    for k in 0..length
	      if if_need_sup
	        new_conf_pos += 11
	      end

	      if (elec_config_element[k] == 's' || elec_config_element[k] == 'p') && elec_config_element[k+1].to_i < 10
	        new_conf[new_conf_pos+1] = '<sup>'+elec_config_element[k+1]+'</sup>'
	        if_need_sup = true
	      elsif elec_config_element[k] == 'd' && elec_config_element[k+1].to_i < 10 && elec_config_element[k+2] == '0' 
	        new_conf[new_conf_pos+1] = '<sup>'+ elec_config_element[k+1]
	        new_conf[new_conf_pos+7] = elec_config_element[k+2] +'</sup>'
	        if_need_sup = true
	      elsif elec_config_element[k] == 'd' && elec_config_element[k+1].to_i < 10
	        new_conf[new_conf_pos+1] = '<sup>'+elec_config_element[k+1] +'</sup>'
	        if_need_sup = true
	      elsif elec_config_element[k] == 'f' && elec_config_element[k+1].to_i < 10 && elec_config_element[k+2].to_i < 5
	        new_conf[new_conf_pos+1] = '<sup>'+elec_config_element[k+1]
	        new_conf[new_conf_pos+7] = elec_config_element[k+2] +'</sup>'
	        if_need_sup = true
	      elsif elec_config_element[k] == 'f' && elec_config_element[k+1].to_i < 10
	        new_conf[new_conf_pos+1] = '<sup>'+elec_config_element[k+1] +'</sup>'
	        if_need_sup = true
	      else 
	        if_need_sup = false
	      end
	      new_conf_pos += 1
	    end
	    new_conf.html_safe
	  else
	  	''
	  end
	end

	def round_to_x_decimals(num,x)
		num.to_f.round(x)
	end
end

app/views/elements/compounds.erb
<div id='wiki'>
  <div id="wiki-menu">
      <span id="size-menu">Information</span>
      <span class="icons"><i class="fa fa-times"></i></span>
      <span class="icons" id="maxmin"><i class="fa fa-minus"></i></button></span>
  </div>
  <div id="info">
    <iframe id="wiki-info" src="" width="99.5%" height="99%" name="SubHtml" scrolling="auto" frameborder="1">
      <p>Texto alternativo para navegadores que no aceptan iframes.</p>
    </iframe>
  </div>
</div>

<!-- Tabla Periodica-elementos -->
<div>
	<table id="periodic-table">
		<tr class="row-header">
			<td id='legend'>
					<table id="box-legend">
						<tr>
							<td id="atomic-number" class="atomic-number"> Z </td>
							<td id="legend-property" class="element-property" colspan="2"> Atomic mass </td>
						</tr>
						<tr>
							<td id="atomic-short" class="atomic-number" colspan="3"> Symbol </td>
						</tr>
						<tr>
							<td id="elect-configuration" class="electron-configuration" colspan="3"> Configuration</td>
						</tr>
						<tr>
							<td id="atomic-name" class="atomic-name" colspan="3">Name </td>
						</tr>
					</table>
					<table id="mass-molecule">
						<tr>
							<td class="molecular-calculator"> Molecular Weight Calculator </td>
						</tr>
						<tr>
							<td> Enter the Molecular Formula: </td>
						</tr>
						<tr>
							<td colspan="2"> 
								<%= form_tag(element_molecule_path) do %>
									<%= text_field_tag :molecule, params[:molecule], placeholder: "Ex. H2O", :size => 20, :class=>"atom-imputs" %> 
									<button><i>Calculate</i></button>
								<% end %>
							</td>
						</tr>
						<tr>
							<td class="mass-result"> <%= @molecular_weight %> </td>
						</tr>
					</table>
			</td>

			<% (1..18).each do |i| %>
				<td id="group<%= i %>" class="group"> <%= i %>  </td>
			<% end %>
		</tr>
		<% i = 0 %>
		<% @matrix_elements.each_with_index do |period, index| %>
			<tr class="row"> 
				<% if index < 7 %>
					<td class="period" id="period<%= index + 1 %>" data-period="<%= index + 1 %>"> 
						<%= index + 1 %> 
					</td>
				<% else %>
					<td> </td>
				<% end %>

				<% period.each do |is_an_element|  %>
					<% if is_an_element == 2 %>
						<% i = i + 15 %>
					<% elsif is_an_element == 3 %>
						<% i = i - 62 %>
					<% elsif is_an_element == 4 %>
						<% i = i + 17 %>
					<% end %>

					<% if is_an_element > 0 && is_an_element < 5  %>
						<td id="element<%= i %>" class="border-element"> 
							<table class="element-box">
								<tr>
									<td class="atomic-number"> <%= @elements[i].atomic_number %> </td>
									<td class="element-property" id="element<%= i %>-property" colspan="2"> <%= round_to_x_decimals(@elements[i].mass, 3) %> </td>
								</tr>
								<tr>
									<td class="atomic-short" colspan="3"> <%= @elements[i].short_name %></td>
								</tr>
								<tr>
									<td class="electron-configuration" colspan="3"> <%= element_configuration(@elements[i].electron_configuration) %> </td>
								</tr>
								<tr>
									<td class="atomic-name" colspan="3"><%= @elements[i].long_name %></td>
								</tr>
							</table>
						</td>
						<% i += 1 %>
					<% elsif is_an_element == 5 %>
						<td class="period period-special" id="period<%= index %>" data-period="<%= index - 2 %>"> <%= index - 2 %> </td>
					<% elsif is_an_element == 6 %>
						<td class="elementoids" id="elementoids<%= index + 1 %>" data-period="<%= index + 1 %>"> <%= (i+1) %> - <%= (i+15) %> </td>
					<% else %>
						<td class="no-border"> </td>
					<% end %>
				<% end %>
			<% end %>
		</tr>
	</table>
</div>

app/views/elements/game.erb
<!-- Tabla Periodica-elementos -->
<div id="periodic-table">
	<table id="limits">
		<tr class="row-header">
			<td id='legend'>
					<div id="game-options">
						<p class='timer'>0:00</p>	
						<button class='btn btn-primary btn-lg btn-block' id="finish-game"> Finish Game </button>			
					</div>
					<table id="random-elements-legend">
						<% (0..1).each do |j| %>
							<tr>
								<% (0..5).each do |i| %>
									<td class="border-element-options" id="random-element<%= i+j*6 %>" data-symbol="">
										<table class="element-box">
											<tr class="atomic-symbol">
												<td class="atomic-short random-atomic-short" id="random-atomic-short<%= i+j*6 %>"  colspan="3"></td>
											</tr>
											<tr class="atom_name">
												<td class="random-atomic-name" id="random-atomic-name<%= i+j*6 %>" colspan="3"> </td>
											</tr>
										</table>
									</td>
								<% end %>
							</tr>
						<% end %>
					</table>
					<div id='second-legend-game'>
						<div>Total score: <span id='score'>0</span></div>
	        </div>
					<div id="successMessageChronometer" class="message">
				    <h2>You did it!</h2>
				    <a href="<%= game_path %>">Play Again</a> 
  				</div>
  				<div id="successMessageTimer" class="message">
				    <h2>Time is over!</h2>
  					<a href="<%= game_path %>">Play Again</a> 
  				</div>
			</td>

			<% (1..18).each do |i| %>
				<td id="group<%= i %>-game" class="group-game"> <%= i %>  </td>
			<% end %>
		</tr>
		<% i = 0 %>
		<% @matrix_elements.each_with_index do |period, index| %>
			<tr class="row"> 
				<% if index < 7 %>
					<td class="period-game" id="period<%= index + 1 %>-game" data-period="<%= index + 1 %>"> 
						<%= index + 1 %> 
					</td>
				<% else %>
					<td> </td>
				<% end %>

				<% period.each do |is_an_element|  %>
					<% if is_an_element == 2 %>
						<% i = i + 15 %>
					<% elsif is_an_element == 3 %>
						<% i = i - 62 %>
					<% elsif is_an_element == 4 %>
						<% i = i + 17 %>
					<% end %>

					<% if is_an_element > 0 && is_an_element < 5  %>
						<td class="border-element-game" id="element-game<%= i %>" data-symbol="<%= @elements[i].short_name %>"> 
							<table class="element-box-game">
								<tr>
									<td class="atomic-short" id="atomic-short<%= i %>" colspan="3"> <%= @elements[i].short_name %></td>
								</tr>
								<tr>
									<td class="atomic-name" id="atomic-name<%= i %>" colspan="3"><%= @elements[i].long_name %></td>
								</tr>
							</table>
						</td>
						<% i += 1 %>
					<% elsif is_an_element == 5 %>
						<td class="period-game period-special-game" id="period<%= index %>-game" data-period="<%= index - 2 %>"> <%= index - 2 %> </td>
					<% elsif is_an_element == 6 %>
						<td class="elementoids-game" id="elementoids<%= index + 1 %>-game" data-period="<%= index + 1 %>"> <%= (i+1) %> - <%= (i+15) %> </td>
					<% else %>
						<td class="no-border-game"> </td>
					<% end %>
				<% end %>
			<% end %>
		</tr>
	</table>
</div>

app/views/elements/home.html.erb
<span class="text-portada">
<h1>PeTaIRON</h1>
	Learn the periodic table in the most enjoyable way!
</span>
<img src="portada.jpg" class="portada">

app/views/elements/index.html.erb
<div id='wiki'>
  <div id="wiki-menu">
      <span id="size-menu">Information</span>
      <span class="icons"><i class="fa fa-times"></i></span>
      <span class="icons" id="maxmin"><i class="fa fa-minus"></i></button></span>
  </div>
  <div id="info">
    <iframe id="wiki-info" src="" width="99.5%" height="99%" name="SubHtml" scrolling="auto" frameborder="1">
      <p>Texto alternativo para navegadores que no aceptan iframes.</p>
    </iframe>
  </div>
</div>

<!-- Tabla Periodica-elementos -->
<div id="periodic-table">
	<table>
		<tr class="row-header">
			<td id='legend'>
					<table id="box-legend">
						<tr>
							<td id="atomic-number" class="atomic-number"> Z </td>
							<td id="legend-property" class="element-property" colspan="2"> Property </td>
						</tr>
						<tr>
							<td id="atomic-short" class="atomic-number" colspan="3"> Symbol</td>
						</tr>
						<tr>
							<td id="elect-configuration" class="electron-configuration" colspan="3"> Configuration </td>
						</tr>
						<tr>
							<td id="atomic-name" class="atomic-name" colspan="3"> Name </td>
						</tr>
					</table>
					<table id="categories-legend">
						<tr>
							<td class="button-category" rowspan="3" data-category="4" data-metal-category="semimetal">Semi Metals</td>
							<td class="button-category" colspan="3" data-metal-category="nonmetal" data-general="nonmetal"> Nonmetals</td>
						<tr>
						</tr>
							<td class="button-category" data-category="5" data-metal-category="nonmetal">Other nonmetals</td>
							<td class="button-category" data-category="6" data-metal-category="nonmetal">Halogen</td>
							<td class="button-category" data-category="7" data-metal-category="nonmetal">Noble Gases</td>
						</tr>
						<tr>
							<td class="button-category" colspan="4" data-metal-category="metal" data-general="metal">Metals</td>
						</tr>
						<tr>
							<td class="button-category" data-category="0" data-metal-category="metal">Alkali Metals</td>
							<td class="button-category" rowspan="2" data-category="2" data-metal-category="metal">Transition Metals</td>
							<td class="button-category" data-category="8" data-metal-category="metal">Lanthanides</td>
							<td class="button-category" rowspan="2" data-category="3" data-metal-category="metal">Basic Metals</td>
						</tr>
						<tr>
							<td class="button-category" data-category="1" data-metal-category="metal">Alkali Earth</td>
							<td class="button-category" data-category="9" data-metal-category="metal">Actinides</td>
						</tr>
					</table>
					<div id="properties-menu-legend" class="container">
						<div class="row-container">
								<div class="col-md-5">
									<input type="radio" id="mass" value="mass" name="property" class="property-button" subname="Atomic Mass">
									<label for="mass">Atomic Mass<span class="property-value" value="mass"></span></label>
								</div>
								<div class="col-md-7">
									<input type="radio" id="state" value="state" name="property" class="property-button" subname="State">
									<label for="state">State (<span class="kelvin">293</span> K)<span class="property-value" value="state"></span></label>
								</div>
						</div>
						<div class="row-container">
								<div class="col-md-5">
									<input type="radio" id="boiling_point" value="boiling_point" name="property" class="property-button" subname="Boiling Tª">
									<label for="boiling_point">Boiling point (K)<span class="property-value" value="boiling_point"></span></label>
								</div>
								<div class="col-md-7">
									<input type="radio" id="ionization_energy" value="ionization_energy" name="property" class="property-button" subname="Ionization Energy">
									<label for="ionization_energy">Ionization energy (kJ/mol)<span class="property-value" value="ionization_energy"></span> </label>
								</div>
						</div>
						<div class="row-container">
								<div class="col-md-5">
									<input type="radio" id="melting_point" value="melting_point" name="property" class="property-button" subname="Melting Tª">
									<label for="melting_point">Melting point (K)<span class="property-value" value="melting_point"></span></label>
								</div>
								<div class="col-md-7">
									<input type="radio" id="electronegativity" value="electronegativity" name="property" class="property-button" subname="Electron Negativity">
									<label for="electronegativity" > Electronegativity<span class="property-value" value="electronegativity"></span></label>
								</div>
						</div>
						<div class="row-container">						
								<div class="col-md-5">
									<input type="radio" id="radium" value="radium" name="property" class="property-button" subname="Radium">
									<label for="radium">Radium (pm)<span class="property-value" value="radium"></span></label>
								</div>
								<div class="col-md-7">
									<input type="radio" id="electron_affinity" value="electron_affinity" name="property" class="property-button" subname="Electron Affinity">
									<label for="electron_affinity">Electron affinity (kJ/mol)<span class="property-value" value="electron_affinity"></span></label>
								</div>
						</div>
						<div class="row-container">
								<div class="col-md-5">
									<input type="radio" id="abundance" value="abundance" name="property" class="property-button" subname="Abundance">
									<label for="abundance">Abundance (%)<span class="property-value" value="abundance"></span></label>
								</div>
								<div class="col-md-7">
									<input type="radio" id="valencies" value="valencies" name="property" class="property-button" subname="valencies">
									<label for="valencies">Valencies<span class="property-value" value="valencies"></span></label>
								</div>
							
						</div>
					</div>
					<div id='first-state-legend'>
						<table id="state-legend">
							<tr>
								<td><div id="solid" class="border-state"> S</div></td>
								<td class="left-align"> Solid</td>
							</tr>
							<tr>
								<td><div id="liquid" class="border-state">L</div></td>
								<td class="left-align"> Liquid</td>
							</tr>
							<tr>
								<td><div class="border-state" id="gas"> G</div></td>
								<td class="left-align"> Gas</td>
							</tr>
							<tr>
								<td><div class="border-state" id="unknown">U </div></td>
								<td class="left-align"> Unknown</td>
							</tr>
						</table>
					</div>
					<div class='temperature-slider'>
				
						<div class="slider-text"><span id="kelvin" class="kelvin">293</span> Kelvin</div>
						<div class="slider-text"><span id="centigrades">20</span> &#8451entigrades</div>
						<div class="slider-text"><span id="fahrenheit">68</span> &#8457ahrenheit</div>
						<div class='slider'>
							<div class='emptyprogress'></div>
							<div class='progress'></div>
							<div class='indicator'></div>
						</div>				
					</div>
				</div> 
				<div id='second-legend'>
					<div class='button-general-properties'>
						<button class='btn btn-primary btn-lg btn-block'> General properties </button>
					</div>
        </div>
			</td>


			<% (1..18).each do |i| %>
				<td id="group<%= i %>" class="group"> <%= i %>  </td>
			<% end %>
		</tr>
		<% i = 0 %>
		<% @matrix_elements.each_with_index do |period, index| %>
			<tr class="row"> 
				<% if index < 7 %>
					<td class="period" id="period<%= index + 1 %>" data-period="<%= index + 1 %>"> <%= index + 1 %> </td>
				<% else %>
					<td> </td>
				<% end %>

				<% period.each do |is_an_element|  %>
					<% if is_an_element == 2 %>
						<% i = i + 15 %>
					<% elsif is_an_element == 3 %>
						<% i = i - 62 %>
					<% elsif is_an_element == 4 %>
						<% i = i + 17 %>
					<% end %>

					<% if is_an_element > 0 && is_an_element < 5  %>
            <td id="element<%= i %>" class="border-element"> 
            
							<table class="element-box">
								<tr>
									<td class="atomic-number"> <%= @elements[i].atomic_number %> </td>
									<td class="element-property" id="element<%= i %>-property" colspan="2">  </td>
								</tr>
								<tr>
									<td class="atomic-short" colspan="3"> <%= @elements[i].short_name %></td>
								</tr>
								<tr>
									<td class="electron-configuration" colspan="3"> <%= element_configuration(@elements[i].electron_configuration) %> </td>
								</tr>
								<tr>
									<td class="atomic-name" colspan="3"><%= @elements[i].long_name %></td>
                </tr>
              </table>
						</td>
						<% i += 1 %>
					<% elsif is_an_element == 5 %>
						<td class="period period-special" id="period<%= index %>" data-period="<%= index - 2 %>"> <%= index - 2 %> </td>
					<% elsif is_an_element == 6 %>
						<td class="elementoids" id="elementoids<%= index + 1 %>" data-period="<%= index + 1 %>"> <%= (i+1) %> - <%= (i+15) %> </td>
					<% else %>
						<td class="no-border"> </td>
					<% end %>
				<% end %>
			<% end %>
		</tr>
	</table>
</div>