config/routes.rb
Rails.application.routes.draw do

  root :to => 'elements#home'
  get '/elements' => 'elements#index'
  get '/properties' => 'elements#property'
  get '/valencies' => 'elements#element_valencies'
  get '/compounds' => 'elements#compounds'
  get '/game' => 'elements#game'
  post '/compounds/molecule' => 'elements#molecule', as: 'element_molecule'
	
  resources :users 
  get 'signup' => 'users#new' 
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :scores

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Petairon</title>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
	<div id="header">
			<ul class="nav">
				<li class="left-margin none"> </li>
				<li class="home-button" data-menu="" data-value=""> <i class="fa fa-home"> </i> Home </li>
				<li class="home-button" id='elements-properties' data-menu="elements" data-value=""> Elements </li>
				<li class="home-button" data-menu="compounds" data-value=""> Compounds </li>
				<li class="home-button" id="game" data-value="-mode" data-menu="game">
					Play! <i class="fa fa-caret-down caret-down" id="caret-down-game"></i></button>
				</li>
				<% if current_user %>
				<ul class="submenu" id="submenu-game-mode">
					<li class="mode-button" data-value="-timer" data-menu="game"><button>Timer Mode</button></li>
						<ul class="submenu-level" id="submenu-game-timer">
							<li><button type="submit" class="start-game" value="easy" data-level="easy">Easy</button></li>
							<li><button type="submit" class="start-game" value="medium" data-level="medium">Medium</button></li>
							<li><button type="submit" class="start-game" value="hard" data-level="hard">Hard</button></li>
							<li><button type="submit" class="start-game" value="expert" data-level="expert">Expert</button></li>
						</ul>
					<li class="mode-button" data-value="-normal" data-menu="game"><button>Normal Mode</button></li>
						<ul class="submenu-level" id="submenu-game-normal">
							<li><button type="submit" class="game-level" value="easy" data-level="easy">Easy</button></li>
							<li><button type="submit" class="game-level" value="medium" data-level="medium">Medium</button></li>
							<li><button type="submit" class="game-level" value="hard" data-level="hard">Hard</button></li>
							<li><button type="submit" class="game-level" value="expert" data-level="expert">Expert</button></li>
						</ul>
				</ul>
				</li>
				<% else %>
					<div id="successMessageLogin" class="message">
				    <h2>You have to log in!</h2>
				    <a href="<%= login_path %>">Log in</a> 
		    		<a href="<%= new_user_path %>">Create an account</a>
					</div>
				<% end %>
			</ul>

			<ul class="nav login-users">
				<li class="left-margin none"> </li>
				<% if current_user %> 
					<li class="home-button img-profile" data-menu="user">
		    			<%= image_tag current_user.image_url.to_s, :class => "img-little-size" %> 
		    			<%= current_user.nick %>
					</li>
					<ul class="none-display submenu" id="submenu-user">
						<li class="menu-option" data-menu="">
				    	<%= link_to "My rankings", user_path(current_user), :class=> "home-button" %>
						</li>
						<li class="menu-option" data-menu="">
				    	<%= link_to "Glogal rankings", scores_path, :class=> "home-button" %>
						</li>
						<li class="menu-option" data-menu="">
				    	<%= link_to "Participants", users_path, :class=> "home-button" %>
						</li>
						<li class="menu-option" data-menu="">
				    	<%= link_to "Edit my profile", edit_user_path(current_user), :class=> "home-button" %>
						</li>
						<hr>
						<li class="menu-option" data-menu="">
				    	<%= link_to "Log out", logout_path, method: "delete", :class=> "home-button" %>
						</li>
					</ul>
		    <% else %> 
		    	<li class="menu-option" data-menu="user">
				    <a href="<%= login_path %>" class="home-button">Log in</a> 
				  </li> 
				  <li class="none">|</li>
				  <li class="menu-option" data-menu="user">
		    		<a href="<%= new_user_path %>" class="home-button">Create an account</a>
		    	</li> 
				<% end %>
			</ul>
		</div>
</header>

<div class="publicity"></div>
<div id="page-wrap">
	<%= yield %>
</div>

<footer> @virgo - Copyleft © 2015 - Legal Notice - Data Protection - Publicity - Cookies Policy</footer>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.0/jquery.min.js"></script>
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.9/jquery-ui.min.js"></script>
</body>
</html>